# imports

In [1]:
import numpy as numpy
import pandas as pd

# load data

In [2]:
# src : https://www.kaggle.com/datasets/jahaidulislam/car-specification-dataset-1945-2020?select=Car+Dataset+1945-2020.csv
df = pd.read_csv("res/car-dataset-1945-2020.csv")
df

/var/folders/_k/5bp3r4wn3nsg0f47hdyhwrhr0000gn/T/ipykernel_35604/1849661473.py:2: DtypeWarning: Columns (0: load_height_mm, 1: length_mm, 2: width_mm, 3: height_mm, 4: wheelbase_mm, 5: front_track_mm, 6: rear_track_mm, 7: curb_weight_kg, 8: ground_clearance_mm, 9: trailer_load_with_brakes_kg, 10: clearance_mm, 11: max_trunk_capacity_l, 12: cargo_volume_m3, 13: overhead_camshaft, 14: cylinder_bore_and_stroke_cycle_mm, 15: turnover_of_maximum_torque_rpm, 16: capacity_cm3, 17: engine_hp_rpm, 18: bore_stroke_ratio, 19: steering_type, 20: battery_capacity_KW_per_h, 21: charging_time_h) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("res/car-dataset-1945-2020.csv")

,id_trim,Make,Modle,Generation,Year_from,Year_to,Series,Trim,Body_type,load_height_mm,...,front_suspension,steering_type,car_class,country_of_origin,number_of_doors,safety_assessment,rating_name,battery_capacity_KW_per_h,electric_range_km,charging_time_h
0,1,AC,ACE,1 generation,1993.0,2000.0,Cabriolet,3.5 MT,Cabriolet,NaN,...,Helical springs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,AC,ACE,1 generation,1993.0,2000.0,Cabriolet,4.6 MT,Cabriolet,NaN,...,Helical springs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,AC,ACE,1 generation,1993.0,2000.0,Cabriolet,4.9 AT,Cabriolet,NaN,...,Helical springs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,AC,ACE,1 generation,1993.0,2000.0,Roadster,2.9 AT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,AC,ACE,1 generation,1993.0,2000.0,Roadster,2.9 MT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70818,70983,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,2.4 AT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70819,70984,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,2.4 MT,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70820,70985,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,2.4 MT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70821,70986,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,3.2 AT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN
70822,70987,ZX,Landmark,1 generation,2007.0,2009.0,SUV 5 doors,3.2 MT 4WD,NaN,NaN,...,NaN,NaN,J,China,5.0,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70823 entries, 0 to 70822
Data columns (total 78 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   id_trim                                   70823 non-null  int64
 1   Make                                      70823 non-null  str
 2   Modle                                     70823 non-null  str
 3   Generation                                70819 non-null  str
 4   Year_from                                 70586 non-null  float64
 5   Year_to                                   70189 non-null  float64
 6   Series                                    70823 non-null  str
 7   Trim                                      70823 non-null  str
 8   Body_type                                 52252 non-null  str
 9   load_height_mm                            3363 non-null   object
 10  number_of_seats                           64696 non-null  str
 11  length_mm                                 64660 non-null  object
 12  width_mm                                  64660 non-null  object
 13  height_mm                                 64660 non-null  object
 14  wheelbase_mm                              64660 non-null  object
 15  front_track_mm                            49473 non-null  object
 16  rear_track_mm                             49473 non-null  object
 17  curb_weight_kg                            53710 non-null  object
 18  wheel_size_r14                            8236 non-null   str
 19  ground_clearance_mm                       39670 non-null  object
 20  trailer_load_with_brakes_kg               13171 non-null  object
 21  payload_kg                                23799 non-null  float64
 22  back_track_width_mm                       11198 non-null  float64
 23  front_track_width_mm                      11204 non-null  float64
 24  clearance_mm                              10523 non-null  object
 25  full_weight_kg                            39682 non-null  float64
 26  front_rear_axle_load_kg                   6357 non-null   str
 27  max_trunk_capacity_l                      42729 non-null  object
 28  cargo_compartment_length_width_height_mm  3337 non-null   str
 29  cargo_volume_m3                           2235 non-null   str
 30  minimum_trunk_capacity_l                  45953 non-null  float64
 31  maximum_torque_n_m                        59598 non-null  str
 32  injection_type                            57680 non-null  str
 33  overhead_camshaft                         1 non-null      str
 34  cylinder_layout                           59544 non-null  str
 35  number_of_cylinders                       59544 non-null  float64
 36  compression_ratio                         6538 non-null   str
 37  engine_type                               59878 non-null  str
 38  valves_per_cylinder                       59334 non-null  float64
 39  boost_type                                23498 non-null  str
 40  cylinder_bore_mm                          51354 non-null  float64
 41  stroke_cycle_mm                           51346 non-null  float64
 42  engine_placement                          6625 non-null   str
 43  cylinder_bore_and_stroke_cycle_mm         5 non-null      str
 44  turnover_of_maximum_torque_rpm            59498 non-null  object
 45  max_power_kw                              7620 non-null   float64
 46  presence_of_intercooler                   12830 non-null  str
 47  capacity_cm3                              59837 non-null  object
 48  engine_hp                                 59877 non-null  float64
 49  engine_hp_rpm                             59408 non-null  object
 50  drive_wheels                              59872 non-null  str
 51  bore_stroke_ratio                         2 non-null      str
 52  number_of_gears                           58292 non-null  float64
 53  turning_circle_m                          40708 non-null  float64
 54  transmission                              59842 non-null  str
 55  mixed_fuel_consumption_per_100_km_l       40566 non-null  float64
 56  range_km                                  33987 non-null  str
 57  emission_standards                        22232 non-null  str
 58  fuel_tank_capacity_l                      57847 non-null  str
 59  acceleration_0_100_km/h_s                 40181 non-null  float64
 60  max_speed_km_per_h                        43074 non-null  str
 61  city_fuel_per_100km_l                     39043 non-null  float64
 62  CO2_emissions_g/km                        1829 non-null   float64
 63  fuel_grade                                58715 non-null  str
 64  highway_fuel_per_100km_l                  38769 non-null  float64
 65  back_suspension                           59454 non-null  str
 66  rear_brakes                               59405 non-null  str
 67  front_brakes                              59799 non-null  str
 68  front_suspension                          59800 non-null  str
 69  steering_type                             2 non-null      str
 70  car_class                                 11765 non-null  str
 71  country_of_origin                         12365 non-null  str
 72  number_of_doors                           13124 non-null  float64
 73  safety_assessment                         1012 non-null   str
 74  rating_name                               1012 non-null   str
 75  battery_capacity_KW_per_h                 15 non-null     str
 76  electric_range_km                         15 non-null     float64
 77  charging_time_h                           7 non-null      str
dtypes: float64(22), int64(1), object(15), str(40)
memory usage: 42.1+ MB

# preprocessing

In [4]:
# Remove unnecessary columns and rename selected columns

columns_to_keep = [
    # Main
    "Make",
    "Modle",
    "Year_from",
    "Year_to",
    "Body_type",
    "car_class",
    "number_of_seats",

    # Engine
    "engine_type",
    "capacity_cm3",
    "engine_hp",
    "maximum_torque_n_m",
    "number_of_cylinders",
    "cylinder_layout",

    # Weight
    "curb_weight_kg",

    # Consumption
    "mixed_fuel_consumption_per_100_km_l",
    "city_fuel_per_100km_l",
    "highway_fuel_per_100km_l",
    "CO2_emissions_g/km",
    "emission_standards",
    "range_km",
    "fuel_grade",

    # Performance
    "acceleration_0_100_km/h_s",
    "max_speed_km_per_h",
]

df = df.loc[:, columns_to_keep].rename(
    columns={
        "Make": "manufacturer",
        "Modle": "model",
        "Year_from": "year_from",
        "Year_to": "year_to",
        "Body_type": "body_type",
        "car_class": "car_class",
        "CO2_emissions_g/km": "co2_emissions_g_per_km",
        "acceleration_0_100_km/h_s": "acceleration_0_100_km_h_s",
    }
)
df

,manufacturer,model,year_from,year_to,body_type,car_class,number_of_seats,engine_type,capacity_cm3,engine_hp,...,curb_weight_kg,mixed_fuel_consumption_per_100_km_l,city_fuel_per_100km_l,highway_fuel_per_100km_l,co2_emissions_g_per_km,emission_standards,range_km,fuel_grade,acceleration_0_100_km_h_s,max_speed_km_per_h
0,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2,Gasoline,3505.0,354.0,...,1510.0,NaN,20.0,9.0,NaN,NaN,"450|1,000",95,5.0,250
1,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2,Gasoline,4601.0,326.0,...,1510.0,NaN,15.0,10.0,NaN,NaN,600|900,98,5.0,250
2,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2,Gasoline,4942.0,260.0,...,1440.0,8.0,NaN,NaN,NaN,NaN,NaN,95,NaN,225
3,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70818,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70819,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70820,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70821,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70822,ZX,Landmark,2007.0,2009.0,NaN,J,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.describe()

,year_from,year_to,engine_hp,number_of_cylinders,mixed_fuel_consumption_per_100_km_l,city_fuel_per_100km_l,highway_fuel_per_100km_l,co2_emissions_g_per_km,acceleration_0_100_km_h_s
count,70586.00000,70189.000000,59877.000000,59544.000000,40566.000000,39043.000000,38769.000000,1829.000000,40181.000000
mean,1997.06524,1913.441978,166.659853,4.972827,8.675676,11.081615,6.985210,156.235648,10.676648
std,14.99201,415.392957,93.269952,1.585268,3.854646,4.477495,2.719996,51.822704,3.608049
min,1904.00000,0.000000,5.000000,1.000000,0.600000,2.100000,2.100000,13.000000,1.970000
25%,1988.00000,1994.000000,105.000000,4.000000,6.200000,8.000000,5.200000,120.000000,8.300000
50%,2000.00000,2005.000000,141.000000,4.000000,7.900000,10.300000,6.300000,146.000000,10.500000
75%,2008.00000,2013.000000,203.000000,6.000000,9.900000,13.100000,8.000000,178.000000,12.500000
max,2020.00000,2020.000000,1914.000000,16.000000,36.500000,43.100000,28.000000,547.000000,50.000000

In [6]:
# Numeric cleaning

# 1. "range_km" stores "city|highway" with thousands separators, e.g. "450|1,000"
range_parts = df["range_km"].astype(str).str.split("|", expand=True)
df["range_city_km"] = pd.to_numeric(
    range_parts[0].str.replace(",", "", regex=False), errors="coerce"
)
df["range_highway_km"] = pd.to_numeric(
    range_parts[1].str.replace(",", "", regex=False), errors="coerce"
)
df = df.drop(columns=["range_km"])

# 2. some columns use "," as a separator, e.g. "157,4" == 157.4, we replace by point only
decimal_comma_cols = [
    "capacity_cm3",
    "maximum_torque_n_m",
    "curb_weight_kg",
    "max_speed_km_per_h",
]
for col in decimal_comma_cols:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace(",", ".", regex=False),
        errors="coerce",
    )

# 3. "number_of_seats" stores multi-config as a list, e.g. "5, 7" (5 or 7 seater), we take the max
seats = df["number_of_seats"].astype(str).str.split(",", expand=True)
df["number_of_seats"] = seats.apply(pd.to_numeric, errors="coerce").max(axis=1)

# Other purely-numeric columns
plain_numeric_cols = [
    "year_from",
    "year_to",
    "engine_hp",
    "number_of_cylinders",
    "mixed_fuel_consumption_per_100_km_l",
    "city_fuel_per_100km_l",
    "highway_fuel_per_100km_l",
    "co2_emissions_g_per_km",
    "acceleration_0_100_km_h_s",
]
df[plain_numeric_cols] = df[plain_numeric_cols].apply(pd.to_numeric, errors="coerce")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70823 entries, 0 to 70822
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   manufacturer                         70823 non-null  str
 1   model                                70823 non-null  str
 2   year_from                            70586 non-null  float64
 3   year_to                              70189 non-null  float64
 4   body_type                            52252 non-null  str
 5   car_class                            11765 non-null  str
 6   number_of_seats                      64597 non-null  float64
 7   engine_type                          59878 non-null  str
 8   capacity_cm3                         59837 non-null  float64
 9   engine_hp                            59877 non-null  float64
 10  maximum_torque_n_m                   59518 non-null  float64
 11  number_of_cylinders                  59544 non-null  float64
 12  cylinder_layout                      59544 non-null  str
 13  curb_weight_kg                       53710 non-null  float64
 14  mixed_fuel_consumption_per_100_km_l  40566 non-null  float64
 15  city_fuel_per_100km_l                39043 non-null  float64
 16  highway_fuel_per_100km_l             38769 non-null  float64
 17  co2_emissions_g_per_km               1829 non-null   float64
 18  emission_standards                   22232 non-null  str
 19  fuel_grade                           58715 non-null  str
 20  acceleration_0_100_km_h_s            40181 non-null  float64
 21  max_speed_km_per_h                   42040 non-null  float64
 22  range_city_km                        33427 non-null  float64
 23  range_highway_km                     32579 non-null  float64
dtypes: float64(16), str(8)
memory usage: 13.0 MB

In [7]:
df.head(50)

,manufacturer,model,year_from,year_to,body_type,car_class,number_of_seats,engine_type,capacity_cm3,engine_hp,...,mixed_fuel_consumption_per_100_km_l,city_fuel_per_100km_l,highway_fuel_per_100km_l,co2_emissions_g_per_km,emission_standards,fuel_grade,acceleration_0_100_km_h_s,max_speed_km_per_h,range_city_km,range_highway_km
0,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2.0,Gasoline,3505.0,354.0,...,NaN,20.0,9.0,NaN,NaN,95,5.0,250.0,450.0,1000.0
1,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2.0,Gasoline,4601.0,326.0,...,NaN,15.0,10.0,NaN,NaN,98,5.0,250.0,600.0,900.0
2,AC,ACE,1993.0,2000.0,Cabriolet,NaN,2.0,Gasoline,4942.0,260.0,...,8.0,NaN,NaN,NaN,NaN,95,NaN,225.0,NaN,NaN
3,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,AC,ACE,1993.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,AC,Aceca,1998.0,2001.0,Coupe,NaN,4.0,Gasoline,3506.0,354.0,...,13.4,20.0,9.0,NaN,NaN,95,5.6,250.0,350.0,780.0
10,AC,Aceca,1998.0,2001.0,Coupe,NaN,4.0,Gasoline,4601.0,307.0,...,NaN,15.1,NaN,NaN,NaN,98,6.1,250.0,460.0,NaN
11,AC,Aceca,1998.0,2001.0,Coupe,NaN,4.0,Gasoline,4601.0,326.0,...,12.2,15.1,10.5,NaN,NaN,98,6.1,250.0,460.0,670.0
12,AC,Cobra,1990.0,2001.0,Roadster,NaN,2.0,Gasoline,4942.0,228.0,...,14.4,17.0,10.0,NaN,NaN,95,5.2,215.0,410.0,700.0
13,AC,Cobra,1990.0,2001.0,Roadster,NaN,2.0,Gasoline,4942.0,250.0,...,NaN,18.0,12.0,NaN,NaN,95,5.2,250.0,390.0,580.0
14,AC,Cobra,1990.0,2001.0,Roadster,NaN,2.0,Gasoline,4942.0,326.0,...,NaN,15.7,10.9,NaN,NaN,95,4.2,250.0,450.0,640.0
15,AC,Cobra,1990.0,2001.0,Roadster,NaN,2.0,Gasoline,4942.0,370.0,...,15.7,18.0,12.0,NaN,NaN,95,5.2,215.0,420.0,630.0
16,AC,Cobra,1990.0,2001.0,Roadster,NaN,2.0,Gasoline,4942.0,340.0,...,NaN,NaN,NaN,NaN,NaN,95,5.0,225.0,NaN,NaN
17,AC,Cobra,1990.0,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,AC,Cobra,1990.0,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,AC,Cobra,1990.0,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,AC,Cobra,1990.0,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,AC,Cobra,1990.0,2001.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Acura,CL,1996.0,2000.0,Coupe,NaN,5.0,Gasoline,2156.0,147.0,...,NaN,11.8,8.4,NaN,NaN,92,8.2,220.0,550.0,770.0
23,Acura,CL,1996.0,2000.0,Coupe,NaN,5.0,Gasoline,2156.0,147.0,...,NaN,9.6,7.6,NaN,NaN,92,8.2,205.0,680.0,860.0
24,Acura,CL,1996.0,2000.0,Coupe,NaN,5.0,Gasoline,2254.0,152.0,...,NaN,11.8,8.4,NaN,NaN,92,8.2,220.0,550.0,770.0
25,Acura,CL,1996.0,2000.0,Coupe,NaN,5.0,Gasoline,2254.0,152.0,...,NaN,9.6,7.6,NaN,NaN,92,8.2,205.0,680.0,860.0
26,Acura,CL,1996.0,2000.0,Coupe,NaN,5.0,Gasoline,2997.0,203.0,...,NaN,11.8,8.4,NaN,NaN,80,NaN,NaN,550.0,770.0
27,Acura,CL,2000.0,2003.0,Coupe,NaN,5.0,Gasoline,3195.0,225.0,...,NaN,12.4,8.1,NaN,NaN,92,7.8,215.0,520.0,800.0
28,Acura,CL,2000.0,2003.0,Coupe,NaN,5.0,Gasoline,3195.0,260.0,...,NaN,12.4,8.1,NaN,NaN,95,6.8,235.0,520.0,800.0
29,Acura,CL,2000.0,2003.0,Coupe,NaN,5.0,Gasoline,3195.0,225.0,...,NaN,12.4,8.1,NaN,NaN,92,7.8,215.0,520.0,800.0
30,Acura,CL,2000.0,2003.0,Coupe,NaN,5.0,Gasoline,3195.0,260.0,...,NaN,12.4,8.4,NaN,NaN,95,6.6,235.0,520.0,770.0
31,Acura,CSX,2006.0,2010.0,Sedan,NaN,5.0,Gasoline,1998.0,157.0,...,NaN,9.5,6.5,NaN,EURO IV,92,NaN,NaN,530.0,770.0
32,Acura,CSX,2006.0,2010.0,Sedan,NaN,5.0,Gasoline,1998.0,157.0,...,NaN,8.7,6.4,NaN,EURO IV,92,NaN,NaN,570.0,780.0
33,Acura,EL,2001.0,2003.0,Sedan,NaN,5.0,Gasoline,1700.0,127.0,...,NaN,7.8,6.1,NaN,NaN,95,NaN,NaN,640.0,820.0
34,Acura,EL,2001.0,2003.0,Sedan,NaN,5.0,Gasoline,1700.0,127.0,...,NaN,7.8,6.1,NaN,NaN,95,NaN,NaN,640.0,820.0
35,Acura,ILX,2018.0,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Acura,Integra,1991.0,2002.0,Coupe,NaN,5.0,Gasoline,1834.0,144.0,...,8.5,9.4,7.6,NaN,NaN,92,6.8,220.0,530.0,660.0
37,Acura,Integra,1991.0,2002.0,Coupe,NaN,5.0,Gasoline,1834.0,144.0,...,8.5,9.4,7.6,NaN,NaN,92,6.8,220.0,530.0,660.0
38,Acura,Integra,1991.0,2002.0,Coupe,NaN,5.0,Gasoline,1797.0,172.0,...,8.4,9.4,7.6,NaN,NaN,95,7.0,214.0,530.0,660.0
39,Acura,Integra,1991.0,2002.0,Coupe,NaN,5.0,Gasoline,1797.0,190.0,...,8.8,9.7,7.8,NaN,NaN,95,6.7,234.0,520.0,640.0
40,Acura,Integra,1991.0,2002.0,Coupe,NaN,5.0,Gasoline,1797.0,197.0,...,8.6,9.4,7.6,NaN,NaN,95,6.6,230.0,530.0,660.0
41,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Acura,Integra,1991.0,2002.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Acura,Integra,1991.0,2002.0,Sedan,NaN,5.0,Gasoline,1834.0,144.0,...,8.4,9.4,7.6,NaN,NaN,80,7.5,205.0,530.0,660.0

In [8]:
# normalize categorical text columns (case + variant spellings)
df["engine_type"] = (
    df["engine_type"]
    .str.lower()
    .replace({"petrol": "gasoline", "diesel fuel": "diesel"})
)

df["cylinder_layout"] = (
    df["cylinder_layout"].str.lower().replace({"-": pd.NA})
)

df["body_type"] = df["body_type"].str.lower()

# emission_standards: unify Roman ("EURO IV") and Arabic ("Euro 4") variants
euro_map = {
    "EURO I": "EURO 1", "EURO II": "EURO 2", "EURO III": "EURO 3",
    "EURO IV": "EURO 4", "EURO V": "EURO 5", "EURO VI": "EURO 6",
    "Euro 2": "EURO 2", "Euro 3": "EURO 3", "Euro 4": "EURO 4",
    "Euro 5": "EURO 5", "Euro 6": "EURO 6",
}
df["emission_standards"] = df["emission_standards"].replace(euro_map)

# fuel_grade: take first listed value (most rows have a single octane like "95")
df["fuel_grade"] = (
    df["fuel_grade"].str.split(",").str[0].str.strip().str.lower()
)

df[["engine_type", "cylinder_layout", "body_type", "emission_standards", "fuel_grade"]].nunique()

engine_type           10
cylinder_layout        8
body_type             15
emission_standards     6
fuel_grade            11
dtype: int64

In [9]:
# Check missing values
df.dropna(how="any")

Empty DataFrame
Columns: [manufacturer, model, year_from, year_to, body_type, car_class, number_of_seats, engine_type, capacity_cm3, engine_hp, maximum_torque_n_m, number_of_cylinders, cylinder_layout, curb_weight_kg, mixed_fuel_consumption_per_100_km_l, city_fuel_per_100km_l, highway_fuel_per_100km_l, co2_emissions_g_per_km, emission_standards, fuel_grade, acceleration_0_100_km_h_s, max_speed_km_per_h, range_city_km, range_highway_km]
Index: []

[0 rows x 24 columns]

# efficiency ratios

In [10]:
df["hp_per_fuel"] = df["engine_hp"] / df["mixed_fuel_consumption_per_100_km_l"]
df["co2_per_hp"] = df["co2_emissions_g_per_km"] / df["engine_hp"]
df["fuel_per_weight"] = df["mixed_fuel_consumption_per_100_km_l"] / df["curb_weight_kg"]

df[[
    "manufacturer", "model", "year_from",
    "engine_hp", "mixed_fuel_consumption_per_100_km_l",
    "curb_weight_kg", "co2_emissions_g_per_km",
    "hp_per_fuel", "co2_per_hp", "fuel_per_weight",
]].head()

,manufacturer,model,year_from,engine_hp,mixed_fuel_consumption_per_100_km_l,curb_weight_kg,co2_emissions_g_per_km,hp_per_fuel,co2_per_hp,fuel_per_weight
0,AC,ACE,1993.0,354.0,NaN,1510.0,NaN,NaN,NaN,NaN
1,AC,ACE,1993.0,326.0,NaN,1510.0,NaN,NaN,NaN,NaN
2,AC,ACE,1993.0,260.0,8.0,1440.0,NaN,32.5,NaN,0.005556
3,AC,ACE,1993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AC,ACE,1993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN